### ISSUE TITLE
User Logout improvements

### ISSUE THREAD

**Issue by Deliquescence** [eramocki/Calendar1998#20]
- [x] Should set current user in mainGUI to null

- [ ] Might be possible to reuse the old loginGUI instead of creating a new one?

**Comment by sramocki** [comment]
https://github.com/eramocki/Calendar1998/compare/4119dbce44af...e5203a80c7fd

Michael did this I believe

**Comment by Deliquescence** [comment]
It is possible to reuse the old GUI but not worth, so this is done
