### ISSUE TITLE
No way to add recurrence end date

### ISSUE THREAD

**Issue by jakurOakland** [eramocki/Calendar1998#42]
We need another date picker in the AddEvent portion of the GUI.

**Comment by sramocki** [comment]
Added, fx:id is recurrenceEndDate

**Comment by sramocki** [comment]
fx:id is recurrenceEndDate

**Comment by jakurOakland** [comment]
Fixed by https://github.com/eramocki/Calendar1998/commit/b0282ee047bab915fbb9a385aab6ef1522f0b146
